### ISSUE TITLE
recursion is broken

### ISSUE THREAD

**Issue by ivarbrandt** [luizoti/script.library.integration.tool#15]
Recursion is disabled or Next Pages is ignored during LIT process.

Revise this to back to work.

**Comment by AlmogLach** [comment]
same problem fails to update all the pages...

**Comment by luizoti** [comment]
Hi, Seren will not supported anymore, it is a piracy  addon, not allowed in kodi forum and etc.

About recursion i will revise in future.

**Comment by ivarbrandt** [comment]
Got it. Thanks for the update.

**Comment by luizoti** [comment]
> Recursion is disabled or Next Pages is ignored during LIT process.
> 
> Revise this to back to work.

Have you tried using recursion only on Seren? Because of the 4 addons currently available, the only one that might be useful is the crunchroll and even so, listing episodes from a list that normally has 30 shows is heavy.

**Comment by ivarbrandt** [comment]
Yeah I've only tried Seren and Fen. But I get that you don't want to support those addons.

**Comment by luizoti** [comment]
@ivarbrandt, they are not supported for reasons of force majeure.

Well if someone else has tested the recursion in some other addon and it didn't work, I need you to report what it was and what situation was tested so that I can check.
