### ISSUE TITLE
stage problem

### ISSUE THREAD

**Issue by AlmogLach** [luizoti/script.library.integration.tool#16]
hi 
i cant stage some movies from seren,venom when i press add all i get error and in the log write that The directory name is invalid in specifics movies.
thanks in advance.

**Comment by luizoti** [comment]
Please, post a log with error.

**Comment by AlmogLach** [comment]
![log](https://user-images.githubusercontent.com/86272484/123491804-50555800-d620-11eb-93ea-9a66bc2728de.png)

**Comment by AlmogLach** [comment]
Its beacuse the colons,the script don't mapp the colon from the name in the addon and windows cannon make a file with colons or special characters please try to fix it.

**Comment by luizoti** [comment]
That's probably right, but I've never tested LIT on windows, as soon as possible, I'll test this.

**Comment by luizoti** [comment]
Good afternoon,

Addons that are outside the Kodi forum rules will no longer be accepted, ser / venon falls under the rules and support will be suspended.

**Comment by AlmogLach** [comment]
Soo what addons do you recommend??

**Comment by luizoti** [comment]
In next revisions of Matrix brunch, this is the working services:

NETFLIX - Works
AMAZON VOD - Works
CRUNCHYROLL - Works
DISNEY+ - Works

Seren will be removed.
