### ISSUE TITLE
Will not added

### ISSUE THREAD

**Issue by djdirty60** [luizoti/script.library.integration.tool#20]
Good day,

Why can't I use the addons Seren and fen through this addon?  Only get errors

**Desktop (please complete the following information):**
 - OS: [android tv]
 - Kodi Version [19.1].

**Kodi log**
http://paste.ubuntu.com/p/YdnJ9VZj4V/

**Comment by luizoti** [comment]
This error is not related with Seren or any other addon.
I fix this error in 'dev' branch, i will submit to Matrix today.

About Seren: #16.

This issue will be close becouse seren is a piracy addon.
