### ISSUE TITLE
TMDBhelper

### ISSUE THREAD

**Issue by rijsab** [luizoti/script.library.integration.tool#28]
Library integration does not work with TMDBhelper addon in Kodi matrix. 

Can this addon be supported please. 
Thanks.

**Comment by luizoti** [comment]
Are TMDB helper or Trakt Collection streaming addons such as Netflix?

**Comment by rijsab** [comment]
Hi,

No not Netflix and was wondering if this is possible. 

Thanks.

**Comment by luizoti** [comment]
From what I read, the TMDB helper is not a straming addon, what is the use of it?

**Comment by rijsab** [comment]
I use TMDBhelper to see in my widgets which files I own as it provides indicators into skins. This addon also let you search through your Trakt lists, trending, popular etc. The addon scrobbles status to Trakt as well and let you integrate Trakt personal lists into Kodi library EXCEPT the entire collection. I want to Integrate my Trakt collection into Kodi Library as the integration will fasten widgets. Hope you are able to support as I already use your addon for my Netflix and Prime Video bit currently missing the TMDBhelper addon.

**Comment by luizoti** [comment]
I suppose it's not possible, but I want to know, the movies you get from your Trakt playlists, how are they played?

**Comment by rijsab** [comment]
Hi,

So I want to integrate my Trakt collection and use Plex to play them on Kodi.

**Comment by luizoti** [comment]
I don't know how Trakt Collection + TMDBhelper + Plex works, but probraly is the Plex that would need to gain support, can you open the plex in your kodi and browse through the contents of your Plex library? (Same is done on netflix when you want to open X or Y movie/series).

**Comment by rijsab** [comment]
Hi,

Yes I am able to open my plex library.

**Comment by luizoti** [comment]
So it's probably Plex that would need to gain support, but at the moment I don't use Plex, where does a Plex library come from?

**Comment by vijayinvites** [comment]
I want this to be supported too. It will be immense help. Or atlast Trakt->Trending list should be supported.

**Comment by luizoti** [comment]
> I want this to be supported too. It will be immense help. Or atlast Trakt->Trending list should be supported.

`So it's probably Plex that would need to gain support, but at the moment I don't use Plex, where does a Plex library come from?`

I need more details or I can't do anything, if possible, let me know or I'll have to close the issue.

**Comment by luizoti** [comment]
Closed.
