### ISSUE TITLE
Add support for Composite

### ISSUE THREAD

**Issue by notoco** [luizoti/script.library.integration.tool#29]
Is it possible to add support for the Composite plugin.
It integrates much better with kodi than the PlexKodiConnect plugin, but doesn't allow you to add individual videos to your library.
https://github.com/anxdpanic/plugin.video.composite_for_plex

**Comment by luizoti** [comment]
Tell me about your setup, how your plex is configured and so on.

I have no idea when I'll be able to look at this, but the fact is I don't use PLEX nor do I have setup to be able to do anything.

Give me a base of your setup maybe help.

**Comment by luizoti** [comment]
> Is it possible to add support for the Composite plugin. It integrates much better with kodi than the PlexKodiConnect plugin, but doesn't allow you to add individual videos to your library. https://github.com/anxdpanic/plugin.video.composite_for_plex

If you explain your setup to me, maybe I'll try to implement it, otherwise I'll close the issue.

**Comment by luizoti** [comment]
Closed.
