### ISSUE TITLE
Error Type: <class 'UnicodeEncodeError'>

### ISSUE THREAD

**Issue by hartontw** [luizoti/script.library.integration.tool#31]
### Issue
Error when adding from staged TV Shows.

### Workaround
1. Go to [Amazon VOD addon](https://github.com/Sandmann79/xbmc) (Primevideo user)
2. Open context menu in Stargate SG-1
3. Add selected item to library as a TV Show
4. From Library Integration Tool -> Staged TV Shows -> Add all TV shows

### Info
- Auto add and create nfo are disabled.
- The first two episodes are managed right.
- I think it fails when processing third episode from first season: ```Emancipación```
- Seems not working right with accents like: ó (\xf3)

### Specs
 - LibreELEC 10.0.1 (Raspberry 4)
 - Kodi Matrix 19.3
 - Localization and Language: es-ES

### Log
```
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
        - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
    Error Type: <class 'UnicodeEncodeError'>
    Error Contents: 'ascii' codec can't encode character '\xf3' in position 147: ordinal not in range(128)
    Traceback (most recent call last):
        File "/storage/.kodi/addons/script.library.integration.tool/default.py", line 33, in <module> 
            main()
        File "/storage/.kodi/addons/script.library.integration.tool/resources/lib/utils.py", line 81, in wrapper
            return func(*args, **kwargs)
        File "/storage/.kodi/addons/script.library.integration.tool/default.py", line 18, in main
            MainMenu(
        File "/storage/.kodi/addons/script.library.integration.tool/resources/lib/menus/main.py", line 102, in view
            command()
        File "/storage/.kodi/addons/script.library.integration.tool/resources/lib/log.py", line 26, in wrapper
            ret = func(*args, **kwargs)
        File "/storage/.kodi/addons/script.library.integration.tool/resources/lib/menus/staged_tv.py", line 407, in view_shows
            command()
        File "/storage/.kodi/addons/script.library.integration.tool/resources/lib/log.py", line 26, in wrapper
            ret = func(*args, **kwargs)
        File "/storage/.kodi/addons/script.library.integration.tool/resources/lib/menus/staged_tv.py", line 143, in add_all_staged_shows_to_library
            item.add_to_library()
        File "/storage/.kodi/addons/script.library.integration.tool/resources/lib/log.py", line 26, in wrapper
            ret = func(*args, **kwargs)
        File "/storage/.kodi/addons/script.library.integration.tool/resources/lib/items/contentmanager.py", line 103, in add_to_library
            create_stream_file(self.file, self.managed_strm_path)
        File "/storage/.kodi/addons/script.library.integration.tool/resources/lib/filesystem.py", line 119, in create_stream_file
            with open(filepath, "w+") as strm:
        UnicodeEncodeError: 'ascii' codec can't encode character '\xf3' in position 147: ordinal not in range(128)
        -->End of Python script error report<--
```

**Comment by dferrg** [comment]
I had the same issue with the first episode from The Boys (also amazon VOD), and some films from TV3Cat. 
I opened a pull-request with a workaround that just removes every non-ascii character from the item title so it can be added to the library. Not the perfect solution but i don't have time for much more.

**Comment by luizoti** [comment]
Normally errors like UnicodeEncodeError shouldn't occur in py3, but as soon as possible I'll try to look at this.

**Comment by luizoti** [comment]
> ### Issue
> Error when adding from staged TV Shows.
> 
> ### Workaround
> 1. Go to [Amazon VOD addon](https://github.com/Sandmann79/xbmc) (Primevideo user)
> 2. Open context menu in Stargate SG-1
> 3. Add selected item to library as a TV Show
> 4. From Library Integration Tool -> Staged TV Shows -> Add all TV shows
> 
> ### Info
> * Auto add and create nfo are disabled.
> * The first two episodes are managed right.
> * I think it fails when processing third episode from first season: `Emancipación`
> * Seems not working right with accents like: ó (\xf3)
> 
> ### Specs
> * LibreELEC 10.0.1 (Raspberry 4)
> * Kodi Matrix 19.3
> * Localization and Language: es-ES
> 
> ### Log
> ```
> EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>         - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>     Error Type: <class 'UnicodeEncodeError'>
>     Error Contents: 'ascii' codec can't encode character '\xf3' in position 147: ordinal not in range(128)
>     Traceback (most recent call last):
>         File "/storage/.kodi/addons/script.library.integration.tool/default.py", line 33, in <module> 
>             main()
>         File "/storage/.kodi/addons/script.library.integration.tool/resources/lib/utils.py", line 81, in wrapper
>             return func(*args, **kwargs)
>         File "/storage/.kodi/addons/script.library.integration.tool/default.py", line 18, in main
>             MainMenu(
>         File "/storage/.kodi/addons/script.library.integration.tool/resources/lib/menus/main.py", line 102, in view
>             command()
>         File "/storage/.kodi/addons/script.library.integration.tool/resources/lib/log.py", line 26, in wrapper
>             ret = func(*args, **kwargs)
>         File "/storage/.kodi/addons/script.library.integration.tool/resources/lib/menus/staged_tv.py", line 407, in view_shows
>             command()
>         File "/storage/.kodi/addons/script.library.integration.tool/resources/lib/log.py", line 26, in wrapper
>             ret = func(*args, **kwargs)
>         File "/storage/.kodi/addons/script.library.integration.tool/resources/lib/menus/staged_tv.py", line 143, in add_all_staged_shows_to_library
>             item.add_to_library()
>         File "/storage/.kodi/addons/script.library.integration.tool/resources/lib/log.py", line 26, in wrapper
>             ret = func(*args, **kwargs)
>         File "/storage/.kodi/addons/script.library.integration.tool/resources/lib/items/contentmanager.py", line 103, in add_to_library
>             create_stream_file(self.file, self.managed_strm_path)
>         File "/storage/.kodi/addons/script.library.integration.tool/resources/lib/filesystem.py", line 119, in create_stream_file
>             with open(filepath, "w+") as strm:
>         UnicodeEncodeError: 'ascii' codec can't encode character '\xf3' in position 147: ordinal not in range(128)
>         -->End of Python script error report<--
> ```

What episode generated the error?

**Comment by hartontw** [comment]
Third episode from season one. 

```S01E03 - Emancipación```

Have some troubles adding content with accents.

**Comment by luizoti** [comment]
Not that this error can't happen with other services, but unfortunately amazon is the most complex to deal with, for you to have an idea the first season doesn't even have episodes here for me, it appears empty. and this is an old issue that i've reported to the devs.

**Comment by hartontw** [comment]
Yes, Amazon VOD is not the most reliable addon. But the same issue is happening with films or episodes with accents.

Anyway, the solution proposed by @dferrg is working for me. This workaround deletes characters with accents or special characters as ```ñ``` but I can generate strm files and with some manual editing and add these to my library. 

Thank you both for your work.

**Comment by luizoti** [comment]
Give me a list with other items, movies/series because I normally use TheBoys in tests, but mainly, in pt-br, accents are common and in py3 I didn't have more errors like this.

**Comment by hartontw** [comment]
I had to undone the patch, I will do it later but my guess is S01E07 from The Boys will fail.

Some other shows and movies I've tried and fail are:
- Law & Order: Criminal Intent (Ley y Orden: Acción Criminal)
- The Office
- Midsome Murders (Los asesinatos de Midsomer)
- Mission: Impossible (Misión Imposible)
- Jurassic Park (Parque Jurásico)

**Comment by luizoti** [comment]
I rewrote the entire filesistem module to use xbmcvfs and the problem seems to be gone, but I don't know when I'll put it online.

**Comment by hartontw** [comment]
Ok, I'll give you feedback when it's ready. Thanks.

**Comment by luizoti** [comment]
Update to version 0.8.34 and confirm that everything is ok.

**Comment by luizoti** [comment]
Here everything seems ok, I'll close the issue for now.

![Screenshot_20220116_181819](https://user-images.githubusercontent.com/29931919/149678430-e5f8310c-722e-408a-9cb7-62f978b79102.png)
