### ISSUE TITLE
plugin.video.seren not integrate tvshows

### ISSUE THREAD

**Issue by trkselim** [luizoti/script.library.integration.tool#8]
Thanks for your great work  you really made my day 

I don’t know if you try   it with seren addon
It’s working fine with movies but I it’s not integrate tv shows

**Comment by luizoti** [comment]
Thanks, I'm happy to be here, this confirmed, it doesn't work, as soon as possible I will check if it is possible to correct it.

I don't know this addon, from what I saw it is free (and that makes me very happy)

**Comment by luizoti** [comment]
@trkselim, 1e029149959eb1e9c5de8bd3e21cd910ce1fe9df, added suport on Leia and Matrix, you can test, issue closed.

**Comment by trkselim** [comment]
Thank you so much now tv shows working 
But it’s integrated the first page from the list 
is there any way to integrate  complete list for movies & tv shows

**Comment by luizoti** [comment]
I intentionally avoid the 'next pages' exactly because in some services it generates an infinite loop.

Disney+ is an example.

**Comment by trkselim** [comment]
One last thing is there anyway to disable creating info file for tv shows

**Comment by luizoti** [comment]
In the settings you have options related to this, but they are on my list of things to be reviewed, if I'm not mistaken they are not working.

**Comment by ivarbrandt** [comment]
It works well for movies in Seren but it's not moving my shows from staged to managed. I don't know what I may be doing wrong. I'm running Kodi 18.9.

**Comment by luizoti** [comment]
Strange, related to Seren, the code is the same for kodi 18 and 19.
About items being moved between staged and managed, if not works with Serem, it wouldn't work with any addom (or should be)
Can you confirm if in fact it is not working? Generates an error and etc?

If it really isn't working, open a new issue explicitly reporting it.

**Comment by ivarbrandt** [comment]
I don't see an error, the show just stays in staged after I try to move it to managed. Shows didn't work in Seren or Fen. Those are the only ones I tried.

No I won't make an issue because I have given up on library integration using plugins. Been at this 3 days now and it's a goddamn mess..not blaming your tool just library integration in general..

**Comment by ivarbrandt** [comment]
Wow my frustration really boiled over. I apologize for taking it out on you. 
I will reinstall Library Integration Tool today and try again.

If I run into any issues I'll provide a more detailed explanation of what is happening.

**Comment by luizoti** [comment]
Ok, i will wait for more info.

**Comment by ivarbrandt** [comment]
Ok so I managed to add movies but I'm still having problems with TV shows.

Heres the steps I've taken:

1. Add single show to library
2. Click on view Staged TV shows in LIT add-on.
3. Click add all TV shows
4. It tells me that all TV shows added
5. Click update library, the kodi scraper starts working and adds the show to my library
6. I go to my library and click the show that was just added and it is completely empty, no seasons, no episodes
7. At this point I go to the managed folders in Settings > Media settings > Library > Videos > script.library.integration.tool > ManagedTV > click on the show and it too is completely empty.

There were no errors thrown throughout the entire process.
It's interesting that TV show integration isn't working for me on Kodi 18.9 but it works on Kodi 19.
What do you think may be happening or what might I be doing wrong?

**Comment by luizoti** [comment]
ok, it seems that at least the show folder was created, can you get what's inside?

What is the format of the title?  if there are files.

**Comment by ivarbrandt** [comment]
UPDATE: Figured it out! It was something wrong with the skin I was using! I switched back to the default skin and all the seasons and episodes were there when I clicked the show!

**Comment by luizoti** [comment]
Perfect, I'm glad it worked, what's the name of the skin?

Just for information, I shouldn't do any major LIT updates for kodi 18, I should just keep kodi 19.

**Comment by ivarbrandt** [comment]
Thanks! The skin is Embuary. I had changed a tiny part in the code to enable different views for Seren but that broke the views for the library content.

Ok good to know. I might upgrade to Kodi 19 in the near future.

So adding movies and TV shows works if I add them one at a time but it gave me an error when trying to add directories from Seren. I had changed the setting 'add without staging' to 'always' for movies and tv shows. It was gathering the content for the first page and then showed an error.

Here's the log of the error. The error is near the bottom.

[kodi.log](https://github.com/luizoti/script.library.integration.tool/files/6690692/kodi.log)

**Comment by luizoti** [comment]
> Thanks! The skin is Embuary. I had changed a tiny part in the code to enable different views for Seren but that broke the views for the library content.
> 
> Ok good to know. I might upgrade to Kodi 19 in the near future.
> 
> So adding movies and TV shows works if I add them one at a time but it gave me an error when trying to add directories from Seren. I had changed the setting 'add without staging' to 'always' for movies and tv shows. It was gathering the content for the first page and then showed an error.
> 
> Here's the log of the error. The error is near the bottom.

The error is:

`UnicodeEncodeError: 'ascii' codec can't encode character u'\xb7' in position 129: ordinal not in range(128)`

The problematic character is: ·

This is a common error in kodi 18 related to py2, in kodi 19 to py3 I suppose it shouldn't happen, try in kodi 19.
If you want, open a issue, in future i can try to fix, but my focus will be kodi 19.

**Comment by ivarbrandt** [comment]
Ok I'll just make the switch to Kodi 19. 

Is there a different repo for Kodi 19? When I add the repo in the readme, it's empty on Kodi 19.

**Comment by luizoti** [comment]
The repo for kodi 19 is the main repo, called Matrix.

**Comment by ivarbrandt** [comment]
Thank you! Got it installed.

It seems like recursion isn't working. It only grabs the items from the first page.
How can I make it grab the items from the next pages?

**Comment by luizoti** [comment]
Current is not possible to get Next Pages, i skip this pages, but in future i will revise this.

**Comment by ivarbrandt** [comment]
Noooo!!!

Ok I understand but hear me out real quick.

Seren's content is spread across multiple pages. The default is 20 items per page. You can change the number of items per page but the max is 100. So if I have a list that has 800 items then the LIT would only get about 13 percent of the items in the list.

I get that using other services could cause an infinite loop but it doesn't with Seren. I tried an old version of LIT and it worked.
So can you tell me what to change in the code to get the recursion working for Seren?

I can't express how important this functionality is for me!

**Comment by luizoti** [comment]
The recursion is in resources.lib.utils in the load_directory_items function.

During the process, the 'Next pages' are ignored with filters, removing these filters should work, but since I changed the load_directory_items function, it might not work correctly.

**Comment by ivarbrandt** [comment]
Ok I don't know much about code but in the load_directory_items there is something called skip_filter. I searched the rest of the code and found that in a def called skip_filter which says it's a generic way to skip Seren's 'next pages'. So would I just delete the entire little section of skip_filter?

**Comment by luizoti** [comment]
re_search and skip_filter functions are connected, the two being connected is not the best way, but it works.
I need to review these two functions and more clearly separate what each does or doesn't do.

This line check if content is a next page:

`if not ('seren' in item['file'] and item['label'] == 'Next'):`

**Comment by ivarbrandt** [comment]
Ok yeah this is beyond my scope of understanding. skip_filter, re_search, and load_directory_items are all tied together. I have no clue what to remove or change there.

**Comment by luizoti** [comment]
The line I mentioned above should solve in seren, but I don't even remember it completely, because I made a quick solution. 
I just don't touch it now because I'm rewriting several (many) pieces of code trying to make it simpler and more optimized.

**Comment by ivarbrandt** [comment]
Ok I tried changing 'Next' to 'N' so if it found Next then it would keep going to the next pages. I also tried removing the 'not' but that made it so that none of the items were grabbed. Lastly, I tried removing the line entirely as well as the 'if not re_search' that way if would just be for 'items in content.json, yield items'. But that didn't work either.

I get that you're busy. I'll just keep an eye out for when you do update it. Thanks.

**Comment by luizoti** [comment]
Well, I recommend that you open a issue, so it will be easier for me to remember.

**Comment by ivarbrandt** [comment]
Ok I will do that.

**Comment by ivarbrandt** [comment]
I made an issue but was very vague since you and I have discussed this at length.
